### ISSUE TITLE
Intermittent off-by-one date error in Analyzer#average_date_for test

### ISSUE THREAD

**Issue by duckinator** [how-is/how_is#21]
Intermittently get the following. I have no idea why, but have a suspicion timezones may be involved (timezones are basically always involved).

```
  1) HowIs::Analyzer#average_date_for returns the average date for the provided issues or pulls
     Failure/Error: expect(result).to eq(Date.parse('2006-01-01'))

       expected: #<Date: 2006-01-01 ((2453737j,0s,0n),+0s,2299161j)>
            got: #<Date: 2005-12-31 ((2453736j,0s,0n),+0s,2299161j)>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -#<Date: 2006-01-01 ((2453737j,0s,0n),+0s,2299161j)>
       +#<Date: 2005-12-31 ((2453736j,0s,0n),+0s,2299161j)>

     # ./spec/how_is/analyzer_spec.rb:26:in `block (3 levels) in <top (required)>'
```

**Comment by duckinator** [comment]
NOT TIMEZONES.

Timestamps are different:

```
  1) HowIs::Analyzer#average_date_for returns the average date for the provided issues or pulls
     Failure/Error: expect(actual.strftime('%s')).to eq(expected.strftime('%s'))

       expected: "1136073600"
            got: "1135987200"

       (compared using ==)
     # ./spec/how_is/analyzer_spec.rb:28:in `block (3 levels) in <top (required)>'
```

**Comment by duckinator** [comment]
I really don't understand how the same code with the same inputs gives different results. There is nothing relying on side-effects.

**Comment by duckinator** [comment]
Apparently switching to DateTime fixed it. The fuck even?

**Comment by duckinator** [comment]
THIS ISSUE IS BACK. I HATE EVERYTHING.

```
  1) HowIs::Analyzer#average_age_for returns the average age for the provided issues or pulls
     Failure/Error: expect(actual).to eq(expected)

       expected: "approximately 10 years and 6 months"
            got: "approximately 10 years and 7 months"

       (compared using ==)
     # ./spec/how_is/analyzer_spec.rb:37:in `block (3 levels) in <top (required)>'
```

**Comment by duckinator** [comment]
Whoops, that was actually a different issue. Both issues mentioned here are now resolved.
