### ISSUE TITLE
`how_is how-is/how_is` is broken

### ISSUE THREAD

**Issue by duckinator** [how-is/how_is#61]
broken: `how_is how-is/how_is`
working: `how_is rubygems/rubygems`

Possibly because there's no PRs for how_is?

backtrace:

```
~/dev/ruby/how-is/how_is$ bundle exec how_is how-is/how_is                                                                  1
bundler: failed to load command: how_is (/home/ellen/dev/ruby/how-is/how_is/.bundle/bin/how_is)
NoMethodError: undefined method `/' for nil:NilClass
  /home/ellen/dev/ruby/how-is/how_is/lib/how_is/analyzer.rb:108:in `average_age_for'
  /home/ellen/dev/ruby/how-is/how_is/lib/how_is/analyzer.rb:43:in `call'
  /home/ellen/dev/ruby/how-is/how_is/.bundle/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
  /home/ellen/dev/ruby/how-is/how_is/.bundle/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
  /home/ellen/dev/ruby/how-is/how_is/.bundle/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /home/ellen/dev/ruby/how-is/how_is/lib/how_is.rb:63:in `generate_analysis'
  /home/ellen/dev/ruby/how-is/how_is/.bundle/gems/contracts-0.14.0/lib/contracts/method_reference.rb:43:in `send_to'
  /home/ellen/dev/ruby/how-is/how_is/.bundle/gems/contracts-0.14.0/lib/contracts/call_with.rb:76:in `call_with'
  /home/ellen/dev/ruby/how-is/how_is/.bundle/gems/contracts-0.14.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /home/ellen/dev/ruby/how-is/how_is/lib/how_is.rb:21:in `generate_report_file'
  /home/ellen/dev/ruby/how-is/how_is/exe/how_is:29:in `<top (required)>'
  /home/ellen/dev/ruby/how-is/how_is/.bundle/bin/how_is:23:in `load'
  /home/ellen/dev/ruby/how-is/how_is/.bundle/bin/how_is:23:in `<top (required)>'
```

**Comment by duckinator** [comment]
There is no case handling no PRs or no issues being open, so it seems likely.
